name: maharishiji
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  get_storage:
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  pin_input_text_field: 4.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg_provider: ^1.0.3
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.0
  animated_text_kit: ^4.2.2
  html: ^0.15.0
  flutter_dotenv: ^5.0.2
  velocity_x:
  chat_gpt_sdk:
  introduction_screen:
  just_audio: ^0.9.34


dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icon/

  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'
